### ISSUE TITLE
network problem in redmi 5 plus vince pex 3.0

### ISSUE THREAD

**Issue by jubabar** [PixelExtended/OTA#207]
does anyone experienced network problem in pex 3.0? I'm experiencing network problem.when i screen lock device for sometimes network goes to emergency calls only.after unlocking it for sometime it comes back.

**Comment by tumon-art** [comment]
**Facing the same problem in Redmi 4.**

**Comment by darkbeast69** [comment]
report to device maintainer or thier support group .
