### ISSUE TITLE
System option from Settings

### ISSUE THREAD

**Issue by Dachoni** [PixelExtended/OTA#213]
Hello! After I try to open System from Settings, the Settings crashes. My device is Redmi 9T (Juice)

Crash log URL: https://hastebin.com/cijareraba

**Comment by KiranPranay** [comment]
Please update to latest Oct release and report in the support group .

**Comment by Dachoni** [comment]
I was unable to log in to my Telegram account. Because I did not receive an SMS, and now I have to wait ..
